import type { Metadata } from "next";
import { Barlow } from "next/font/google";
import { Header, Footer, WhatsAppFloatingButton } from "@/components/shared";
import { Toaster } from "@/components/ui/toaster";
import CategoryProvider from "@/contexts/CategoryProvider";
import { GoogleAnalytics } from '@next/third-parties/google'

import "./globals.css";
import Script from "next/script";

const barlow = Barlow({
  weight: ["200", "400", "700", "800"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "ZOAN",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <CategoryProvider>
        <body className={barlow.className}>
          <Header />
          {children}
          <Footer />
          <noscript>
            <iframe src="https://www.googletagmanager.com/ns.html?id=GTM-MMTK8WQ8" height="0" width="0"
                    style={{ display: 'none', visibility: 'hidden' }}>
            </iframe>
          </noscript>
          <Script async src="https://www.googletagmanager.com/gtag/js?id=G-K0Y3E4ZJEE"></Script>
          <Toaster />
          <WhatsAppFloatingButton />
        </body>
        <GoogleAnalytics gaId="G-K0Y3E4ZJEE"/>
      </CategoryProvider>
    </html>
  );
}
