import type { Metadata } from "next";
import { Barlow } from "next/font/google";
// import NavigationMenu from "@/components/shared/navigation/NavigationMenu";
import Header from "@/components/shared/header/Header";
import "./globals.css";

const barlow = Barlow({
	weight: ["200", "400", "700", "800"],
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "ZOAN",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={barlow.className}>
				<Header />
				{children}
			</body>
		</html>
	);
}
